# Generated by Django 3.0.2 on 2020-02-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200228_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='awarded',
            field=models.BooleanField(default=False),
        ),
    ]
