# Generated by Django 3.0.2 on 2020-02-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_projects_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Projects'),
        ),
    ]
