# Generated by Django 3.0.2 on 2020-02-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='+254740368934', max_length=12, verbose_name='Phone Number'),
        ),
    ]
